version: '3'
services:
    api:
        container_name: huskyCI_API
        environment:
            GOPATH: /go/
            # required envs
            HUSKYCI_DATABASE_DB_ADDR: mongodb
            HUSKYCI_DATABASE_DB_NAME: ${HUSKYCI_DATABASE_DB_NAME}
            HUSKYCI_DATABASE_DB_USERNAME: ${HUSKYCI_DATABASE_DB_USERNAME}
            HUSKYCI_DATABASE_DB_PASSWORD: ${HUSKYCI_DATABASE_DB_PASSWORD}
            HUSKYCI_API_DEFAULT_USERNAME: ${HUSKYCI_API_DEFAULT_USERNAME}
            HUSKYCI_API_DEFAULT_PASSWORD: ${HUSKYCI_API_DEFAULT_PASSWORD}
            HUSKYCI_API_ALLOW_ORIGIN_CORS: "*"
            HUSKYCI_DOCKERAPI_ADDR: ${HUSKYCI_DOCKERAPI_ADDR}
            HUSKYCI_DOCKERAPI_CERT_PATH: /certs/
        build:
            context: ../
            dockerfile: deployments/dockerfiles/api.Dockerfile
        command: "go run server.go"
        volumes:
            - ${HUSKYCI_CERT_PATH}/api:/certs:ro
        ports:
          - "8888:8888"
        networks:
            - huskyCI_net
        depends_on:
            - mongodb

    mongodb:
        container_name: huskyCI_MongoDB
        environment:
            DATABASE: ${HUSKYCI_DATABASE_DB_NAME}
            DATABASE_USER: ${HUSKYCI_DATABASE_DB_USERNAME}
            DATABASE_PASS: ${HUSKYCI_DATABASE_DB_PASSWORD}
        build:
            context: ../
            dockerfile: deployments/dockerfiles/db.Dockerfile
        volumes:
            - mongo_vol:/data/db
        networks:
            - huskyCI_net

networks:
    huskyCI_net:

volumes:
    mongo_vol:
