version: '3'
services:
    api:
        container_name: huskyci-api
        environment:
            HUSKYCI_DATABASE_DB_ADDR: mongodb
            HUSKYCI_DATABASE_DB_NAME: ${HUSKYCI_DATABASE_DB_NAME}
            HUSKYCI_DATABASE_DB_USERNAME: ${HUSKYCI_DATABASE_DB_USERNAME}
            HUSKYCI_DATABASE_DB_PASSWORD: ${HUSKYCI_DATABASE_DB_PASSWORD}
            HUSKYCI_API_DEFAULT_USERNAME: ${HUSKYCI_API_DEFAULT_USERNAME}
            HUSKYCI_API_DEFAULT_PASSWORD: ${HUSKYCI_API_DEFAULT_PASSWORD}
            HUSKYCI_API_ALLOW_ORIGIN_CORS: ${HUSKYCI_API_ALLOW_ORIGIN_CORS}
            HUSKYCI_DOCKERAPI_ADDR: ${HUSKYCI_DOCKERAPI_ADDR}
            HUSKYCI_DOCKERAPI_CERT_PATH: /certs/
        image: huskyci-api
        build:
            context: ../
            dockerfile: deployments/dockerfiles/api.Dockerfile
        volumes:
            - ${HUSKYCI_PATH}/api/config.yaml:/app/config.yaml
            - ${HUSKYCI_CERT_PATH}/api:/certs:ro
        ports:
          - "8888:8888"
        networks:
            - huskyCI_net
        depends_on:
            - mongodb
        restart: always

    mongodb:
        container_name: huskyci-mongodb
        image: huskyci-mongodb
        build:
            context: ../
            dockerfile: deployments/dockerfiles/db.Dockerfile
        volumes:
            - mongo_vol:/data/db
        networks:
            - huskyCI_net

networks:
    huskyCI_net:

volumes:
    mongo_vol:
